modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = "https://github.com/Stonebound/SimpleIRCBridge"
license = "BSD-2-Clause"

[[mods]]
modId = "simpleircbridge"
version = "${version}"
displayName = "simple irc bridge"
authors = "Xnrand & contributors"
description = '''
simple irc bridge stonebound fork
'''
#logoFile = ""

[[dependencies.simpleircbridge]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.simpleircbridge]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.simpleircbridge]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "SERVER"
