modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = "https://github.com/Stonebound/SimpleIRCBridge"
license = "BSD-2-Clause"

[[mods]]
modId = "simpleircbridge"
version = "${version}"
displayName = "simple irc bridge"
authors = "Xnrand & contributors"
description = '''
simple irc bridge stonebound fork
'''
#logoFile = ""

[[dependencies.simpleircbridge]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simpleircbridge]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simpleircbridge]]
modId = "architectury"
type = "required"
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "simpleircbridge.mixins.json"
